---
- name: Deploy Weather App
  hosts: web
  become: yes

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Python3 and pip3
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask and Requests
      pip:
        name:
          - Flask
          - requests
        executable: pip3

    - name: Create app directory
      file:
        path: /opt/weather-app
        state: directory

    - name: Copy application code
      copy:
        src: ../app/
        dest: /opt/weather-app/
    
    - name: Run the Flask app
      shell: |
        nohup python3 /opt/weather-app/server.py > /opt/weather-app/output.log 2>&1 &
      args:
        executable: /bin/bash
